{% set name = "regi0" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/regi0-{{ version }}.tar.gz
  sha256: df40db19d9d8223203a6cc4d0058721e79a237dbb5398a0f48fcd69a9e9487fb
build:
  number: 0
  noarch: python
  entry_points:
    - regi0 = regi0.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - appdirs
    - click
    - fiona
    - geopandas >=0.10
    - numpy >=1.15
    - openpyxl
    - pandas
    - pygeos
    - python >=3.6,<3.10
    - rapidfuzz
    - rasterio >=1.2
    - rasterstats
    - requests
    - rtree
    - scipy
    - shapely

test:
  imports:
    - regi0
  commands:
    - pip check
    - regi0 --help
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/regi0
  summary: A Python toolkit to complement and verify biological records.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla
