{% set name = "regi0" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/regi0-{{ version }}.tar.gz
  sha256: 27f89093f0ac3969b3be4fc05158ebf58e9926d6c5aab6a24c04733d5d6260a8

build:
  entry_points:
    - regi0 = regi0.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<3.10
    - tomli
  run:
    - appdirs
    - click
    - fiona
    - geopandas >=0.10
    - numpy >=1.15
    - openpyxl
    - pandas
    - pygeos
    - python >=3.7,<3.10
    - rapidfuzz
    - rasterio >=1.2
    - rasterstats
    - requests
    - scipy

test:
  imports:
    - regi0
  commands:
    - pip check
    - regi0 --help
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/regi0
  summary: A Python toolkit to complement and verify biological records.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla