{% set name = "regi0" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/regi0-{{ version }}.tar.gz
  sha256: 5bd4410c68e36d3822ed562c8a99c51e8aa38811854288d4ee37d3cf724c63b7

build:
  number: 0
  noarch: python
  entry_points:
    - regi0 = regi0.cli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - appdirs
    - click
    - fiona
    - geopandas >=0.10
    - numpy >=1.15
    - openpyxl
    - pandas
    - pygeos
    - python >=3.6,<3.10
    - rapidfuzz
    - rasterio >=1.2
    - rasterstats
    - requests
    - rtree
    - scipy
    - shapely

test:
  imports:
    - regi0
  commands:
    - pip check
    - regi0 --help
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/regi0
  summary: A Python toolkit to complement and verify biological records.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla
